version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      target: development
    command: >
      sh -c "
        pnpm migrate:up &&
        while ! curl -s http://web:3000 > /dev/null; do
          echo 'Waiting for web service to be ready...'
          sleep 2
        done &&
        curl -X POST http://web:3000/api/seed"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/solaceassignment

  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/solaceassignment
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  psql:
